/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Presentacion;

import Entidades.Album;
import Entidades.Interprete;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import javax.swing.JComboBox;
import modelo.FuncionesDAO;

/**
 *
 * @author estudiante
 */
public class PantallaAdministrador extends javax.swing.JFrame {

    /**
     * Creates new form PantallaAdministrador
     */
    public PantallaAdministrador() {
        initComponents();
        llenarComboBoxPaises();
        llenarComboBoxEmpresasDiscograficas();
        llenarComboBoxIdiomas();
        llenarComboBoxGeneros();
        llenarComboBoxCanciones();
        llenarCOmboBoxArtistas(comboBoxArtistaSecundario);
        llenarCOmboBoxArtistas(comboBoxInterpretePrincipal);
        llenarComboBoxAlbumes ();
        
    }
    public void verEstadisticas (){
        PantallaEstadisticas pEstadisticas = new PantallaEstadisticas();
        pEstadisticas.setVisible(true);
        dispose();
    }
    public void cerrarSesion (){
        PantallaLogin pantallaLogin = new PantallaLogin();
        pantallaLogin.setVisible(true);
        dispose();
    }
    public final void llenarComboBoxPaises(){
        FuncionesDAO admin = new FuncionesDAO();
        admin.rellenarPaises(comboBoxPais);
    }
    public final void llenarComboBoxEmpresasDiscograficas (){
         FuncionesDAO admin = new FuncionesDAO();
         admin.rellenarEmpresasDiscograficas(comboBoxEmpresaDiscografica);
    }
    public final void llenarComboBoxIdiomas (){
        FuncionesDAO admin = new FuncionesDAO();
        admin.rellenarIdiomas(comboBoxIdiomaTituloCancion);
    }
    public final void llenarComboBoxGeneros(){
         FuncionesDAO admin = new FuncionesDAO();
         admin.rellenarGeneros(comboBoxGeneroCancion);
    }
    public final void llenarComboBoxCanciones(){
        FuncionesDAO admin =new FuncionesDAO();
        admin.rellenarCanciones(comboBoxCancion);
    }
    public final void llenarCOmboBoxArtistas(JComboBox comboBox){
        FuncionesDAO admin = new FuncionesDAO();
        admin.rellenarArtistas(comboBox);
    }
    public final void actualizarcomboBoxArtistas(){
        comboBoxArtistaSecundario.removeAllItems();
        comboBoxInterpretePrincipal.removeAllItems();
        FuncionesDAO admin = new FuncionesDAO();
        admin.rellenarArtistas(comboBoxArtistaSecundario);
        admin.rellenarArtistas(comboBoxInterpretePrincipal);
    }
    public final void actualizarComboBoxAlbum (){
        FuncionesDAO admin = new FuncionesDAO();
        comboBoxAlbumCancion.removeAllItems();
        admin.rellenarAlbumes(comboBoxAlbumCancion);
    }
    public final void actualizarComboBoxCancion (){
        FuncionesDAO admin = new FuncionesDAO();
        comboBoxCancion.removeAllItems();
        admin.rellenarCanciones(comboBoxCancion);
    }

    private void llenarComboBoxAlbumes() {
        FuncionesDAO admin = new FuncionesDAO();
        admin.rellenarAlbumes(comboBoxAlbumCancion);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AlbumOEP = new javax.swing.ButtonGroup();
        LabelAgregarAlbumOEp = new javax.swing.JLabel();
        textFieldTituloAlbum = new javax.swing.JTextField();
        botonAgregarAlbum = new javax.swing.JButton();
        LabelAgregarArtista = new javax.swing.JLabel();
        labelTituloAlbum = new javax.swing.JLabel();
        textFieldFechaLanzamiento = new javax.swing.JTextField();
        labelFechaLanzamiento = new javax.swing.JLabel();
        textFieldNombreArtista = new javax.swing.JTextField();
        labelNombreArtista = new javax.swing.JLabel();
        textFieldNombreArtistico = new javax.swing.JTextField();
        labelNombreArtistico = new javax.swing.JLabel();
        labelPais = new javax.swing.JLabel();
        buttonAgregarArtista = new javax.swing.JButton();
        comboBoxPais = new javax.swing.JComboBox<>();
        labelAlbumOEp = new javax.swing.JLabel();
        rbuttonAlbum = new javax.swing.JRadioButton();
        rbuttonEP = new javax.swing.JRadioButton();
        LabelAgregarCancionAAlbum = new javax.swing.JLabel();
        textFieldDuracionCancion = new javax.swing.JTextField();
        labelDuracionCancion = new javax.swing.JLabel();
        labelGeneroCancion = new javax.swing.JLabel();
        labelInterpretePrincipal = new javax.swing.JLabel();
        comboBoxGeneroCancion = new javax.swing.JComboBox<>();
        comboBoxInterpretePrincipal = new javax.swing.JComboBox<>();
        botonAgregarCancion = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        comboBoxCancion = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        comboBoxArtistaSecundario = new javax.swing.JComboBox<>();
        botonAgregarArtistaSecundario = new javax.swing.JButton();
        labelIdiomaTitulo = new javax.swing.JLabel();
        comboBoxIdiomaTituloCancion = new javax.swing.JComboBox<>();
        lableTituloCancion = new javax.swing.JLabel();
        textFieldTituloCancion = new javax.swing.JTextField();
        comboBoxAlbumCancion = new javax.swing.JComboBox<>();
        labelAlbumxCancion = new javax.swing.JLabel();
        buttonCerrarSesion = new javax.swing.JButton();
        comboBoxEmpresaDiscografica = new javax.swing.JComboBox<>();
        textoResultadoArtista = new javax.swing.JLabel();
        textoResultadoAgregarAlbum = new javax.swing.JLabel();
        textoResultadoAgregarArtistaSecundario = new javax.swing.JLabel();
        textoResultadoAgregarCancion = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        BotonEstadisticas = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        LabelAgregarAlbumOEp.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        LabelAgregarAlbumOEp.setText("Agregar Album o EP");

        textFieldTituloAlbum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldTituloAlbumActionPerformed(evt);
            }
        });

        botonAgregarAlbum.setText("Agregar Album");
        botonAgregarAlbum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAgregarAlbumActionPerformed(evt);
            }
        });

        LabelAgregarArtista.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        LabelAgregarArtista.setText("Agregar Artista");

        labelTituloAlbum.setText("Titulo");

        textFieldFechaLanzamiento.setText("dd-mm-yyyy");
        textFieldFechaLanzamiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldFechaLanzamientoActionPerformed(evt);
            }
        });

        labelFechaLanzamiento.setText("Fecha Lanzamiento");

        textFieldNombreArtista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldNombreArtistaActionPerformed(evt);
            }
        });

        labelNombreArtista.setText("Nombre");

        textFieldNombreArtistico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldNombreArtisticoActionPerformed(evt);
            }
        });

        labelNombreArtistico.setText("NombreArtistico");

        labelPais.setText("Pais");

        buttonAgregarArtista.setText("Agregar Artista");
        buttonAgregarArtista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAgregarArtistaActionPerformed(evt);
            }
        });

        comboBoxPais.setToolTipText("");

        labelAlbumOEp.setText("Album o ep");

        AlbumOEP.add(rbuttonAlbum);
        rbuttonAlbum.setText("Album");
        rbuttonAlbum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbuttonAlbumActionPerformed(evt);
            }
        });

        AlbumOEP.add(rbuttonEP);
        rbuttonEP.setText("EP");

        LabelAgregarCancionAAlbum.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        LabelAgregarCancionAAlbum.setText("Agregar Cancion A Album");

        textFieldDuracionCancion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldDuracionCancionActionPerformed(evt);
            }
        });

        labelDuracionCancion.setText("Druracion");

        labelGeneroCancion.setText("Genero");

        labelInterpretePrincipal.setText("Interprete Principal");

        comboBoxInterpretePrincipal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxInterpretePrincipalActionPerformed(evt);
            }
        });

        botonAgregarCancion.setText("Agregar Cancion");
        botonAgregarCancion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAgregarCancionActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabel10.setText("Agregar artistas secundarios a cancion");

        comboBoxCancion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxCancionActionPerformed(evt);
            }
        });

        jLabel14.setText("Cancion");

        jLabel15.setText("Artista");

        comboBoxArtistaSecundario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxArtistaSecundarioActionPerformed(evt);
            }
        });

        botonAgregarArtistaSecundario.setText("Agregar Artista");
        botonAgregarArtistaSecundario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAgregarArtistaSecundarioActionPerformed(evt);
            }
        });

        labelIdiomaTitulo.setText("IdiomaTitulo");

        lableTituloCancion.setText("titulo");

        labelAlbumxCancion.setText("Album");

        buttonCerrarSesion.setText("Cerrar sesion");
        buttonCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCerrarSesionActionPerformed(evt);
            }
        });

        comboBoxEmpresaDiscografica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxEmpresaDiscograficaActionPerformed(evt);
            }
        });

        textoResultadoArtista.setForeground(new java.awt.Color(255, 0, 51));
        textoResultadoArtista.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        textoResultadoAgregarAlbum.setForeground(new java.awt.Color(255, 0, 0));
        textoResultadoAgregarAlbum.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        textoResultadoAgregarArtistaSecundario.setForeground(new java.awt.Color(204, 0, 0));

        textoResultadoAgregarCancion.setForeground(new java.awt.Color(255, 0, 0));
        textoResultadoAgregarCancion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Mostrar Estadisticas");

        BotonEstadisticas.setText("Mostrar");
        BotonEstadisticas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonEstadisticasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(121, 121, 121)
                                .addComponent(buttonAgregarArtista))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(49, 49, 49)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(textoResultadoArtista, javax.swing.GroupLayout.DEFAULT_SIZE, 286, Short.MAX_VALUE)
                                        .addGap(93, 93, 93)
                                        .addComponent(botonAgregarAlbum)
                                        .addGap(112, 112, 112))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(LabelAgregarArtista)
                                            .addComponent(textFieldNombreArtista)
                                            .addComponent(labelNombreArtistico)
                                            .addComponent(textFieldNombreArtistico, javax.swing.GroupLayout.DEFAULT_SIZE, 253, Short.MAX_VALUE)
                                            .addComponent(labelNombreArtista, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(labelPais)
                                            .addComponent(comboBoxPais, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGap(41, 41, 41)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(LabelAgregarAlbumOEp)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(rbuttonAlbum)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(rbuttonEP))
                                            .addComponent(labelAlbumOEp)
                                            .addComponent(textFieldTituloAlbum, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(labelTituloAlbum)
                                            .addComponent(labelFechaLanzamiento)
                                            .addComponent(textFieldFechaLanzamiento, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(comboBoxEmpresaDiscografica, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(textoResultadoAgregarAlbum, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGap(4, 4, 4)
                                        .addComponent(textoResultadoAgregarArtistaSecundario, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 84, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(97, 97, 97)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(comboBoxCancion, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel14))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(BotonEstadisticas)
                                .addGap(105, 105, 105))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(comboBoxArtistaSecundario, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel15)
                                    .addComponent(botonAgregarArtistaSecundario))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel10)
                        .addGap(73, 73, 73)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(LabelAgregarCancionAAlbum)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(labelInterpretePrincipal)
                                        .addComponent(labelDuracionCancion)
                                        .addComponent(labelGeneroCancion)
                                        .addComponent(comboBoxInterpretePrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(textFieldTituloCancion, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(textFieldDuracionCancion, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(comboBoxGeneroCancion, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(6, 6, 6)
                                            .addComponent(lableTituloCancion))
                                        .addComponent(comboBoxIdiomaTituloCancion, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(labelIdiomaTitulo))
                                    .addComponent(labelAlbumxCancion, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(comboBoxAlbumCancion, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(botonAgregarCancion)
                                    .addGap(75, 75, 75))
                                .addComponent(textoResultadoAgregarCancion, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(128, 128, 128))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(buttonCerrarSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(55, 55, 55))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(LabelAgregarArtista)
                        .addComponent(LabelAgregarAlbumOEp))
                    .addComponent(buttonCerrarSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(labelNombreArtista, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(labelAlbumOEp))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(textFieldNombreArtista, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(rbuttonAlbum)
                                    .addComponent(rbuttonEP))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(labelNombreArtistico)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(textFieldNombreArtistico, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(labelPais)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(comboBoxPais, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(buttonAgregarArtista, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(textoResultadoArtista, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(10, 10, 10))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(12, 12, 12)
                                        .addComponent(comboBoxEmpresaDiscografica)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(botonAgregarAlbum)
                                        .addGap(4, 4, 4))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(labelTituloAlbum)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(textFieldTituloAlbum, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(labelFechaLanzamiento)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(textFieldFechaLanzamiento, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(106, 106, 106)))
                        .addComponent(textoResultadoAgregarAlbum, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(comboBoxCancion, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(comboBoxArtistaSecundario, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(botonAgregarArtistaSecundario)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textoResultadoAgregarArtistaSecundario, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(LabelAgregarCancionAAlbum)
                        .addGap(18, 18, 18)
                        .addComponent(labelIdiomaTitulo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(comboBoxIdiomaTituloCancion, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lableTituloCancion)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textFieldTituloCancion, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(labelDuracionCancion)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textFieldDuracionCancion, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelGeneroCancion)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(comboBoxGeneroCancion, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelInterpretePrincipal)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(comboBoxInterpretePrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelAlbumxCancion, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BotonEstadisticas))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(comboBoxAlbumCancion, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(botonAgregarCancion)
                        .addGap(3, 3, 3)
                        .addComponent(textoResultadoAgregarCancion, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(51, 51, 51))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonAgregarAlbumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAgregarAlbumActionPerformed
        FuncionesDAO admin = new FuncionesDAO();
        
        int codigoAlbum= admin.obtenerProximoIdAlbum();
        String titulo = textFieldTituloAlbum.getText();
        String fecha = textFieldFechaLanzamiento.getText();
        
        java.util.Date utilFecha = null;

        try {
            utilFecha = new SimpleDateFormat("dd-MM-yyyy").parse(fecha);
        } catch (ParseException ex) {
            ex.printStackTrace();
        }

        java.sql.Date sqlFecha = null;
        if (utilFecha != null) {
            sqlFecha = new java.sql.Date(utilFecha.getTime());
        }
        String empresaDiscografica= (String) comboBoxEmpresaDiscografica.getSelectedItem();
        int idEmpresaDiscografica= 1;
        String albumOEP = rbuttonAlbum.isSelected() ? "album" : "ep";
        
        Album album= new Album(codigoAlbum, titulo, sqlFecha, idEmpresaDiscografica, albumOEP);
        boolean agregoAlbum =admin.agregarAlbumOEp(album);
        if (agregoAlbum){
            textoResultadoAgregarAlbum.setText("Se Agrego el album correctamente");
        }
        else{
            textoResultadoAgregarAlbum.setText("Ocurrio un error al agregar el album");
        }
        actualizarComboBoxAlbum();
    }//GEN-LAST:event_botonAgregarAlbumActionPerformed

    private void textFieldTituloAlbumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldTituloAlbumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldTituloAlbumActionPerformed

    private void textFieldFechaLanzamientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldFechaLanzamientoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldFechaLanzamientoActionPerformed

    private void textFieldNombreArtistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldNombreArtistaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldNombreArtistaActionPerformed

    private void textFieldNombreArtisticoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldNombreArtisticoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldNombreArtisticoActionPerformed

    private void buttonAgregarArtistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAgregarArtistaActionPerformed
        FuncionesDAO admin = new FuncionesDAO();
        String nombre= textFieldNombreArtista.getText();
        String nombreArtistico = textFieldNombreArtistico.getText();
        String pais= (String) comboBoxPais.getSelectedItem();
        int idPais = admin.convertirPaisAID(pais);
        int idArtista= admin.obtenerProximoIdInteprete();
        Interprete artista= new Interprete(idArtista, nombre, nombreArtistico, idPais);
        boolean sePudoAgregar=admin.agregarArtista(artista);
        if (sePudoAgregar){
            textoResultadoArtista.setText("Agregado existosamente");
        }
        else{
            textoResultadoArtista.setText("Ocurrio un error al agregar el artista");
        }
        actualizarcomboBoxArtistas();
        
        
    }//GEN-LAST:event_buttonAgregarArtistaActionPerformed

    private void rbuttonAlbumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbuttonAlbumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbuttonAlbumActionPerformed

    private void textFieldDuracionCancionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldDuracionCancionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldDuracionCancionActionPerformed

    private void botonAgregarCancionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAgregarCancionActionPerformed
        FuncionesDAO admin = new FuncionesDAO();
        String idiomaTitulo = (String) comboBoxIdiomaTituloCancion.getSelectedItem();
        String titulo = textFieldTituloCancion.getText();
        int duracion = Integer.parseInt(textFieldDuracionCancion.getText());
        String genero = (String) comboBoxGeneroCancion.getSelectedItem();
        String interPretePrincipal = (String) comboBoxInterpretePrincipal.getSelectedItem();
        String album = (String) comboBoxAlbumCancion.getSelectedItem();
        //boolean creoCancion= admin.crearCancionYAsignarTituloYAlbum(idiomaTitulo, titulo, duracion, genero, interPretePrincipal, album);
        boolean creoCancion=true;
        if (creoCancion){
            textoResultadoAgregarCancion.setText("se agrego la cancion");
        }
        else {
            textoResultadoAgregarCancion.setText("Ocurrio un error al agregar la cancion");
        }
        actualizarComboBoxCancion();
    }//GEN-LAST:event_botonAgregarCancionActionPerformed

    private void botonAgregarArtistaSecundarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAgregarArtistaSecundarioActionPerformed
        FuncionesDAO admin = new FuncionesDAO();
        String cancion = (String) comboBoxCancion.getSelectedItem();
        String aritsta = (String) comboBoxArtistaSecundario.getSelectedItem();
        boolean agregado = admin.agregarInterpretesXCancion(cancion, aritsta);
        if (agregado){
            textoResultadoAgregarArtistaSecundario.setText("Agregado Correctamete");
        }
        else{
            textoResultadoAgregarArtistaSecundario.setText("No se pudo agregar el artista secundario");
        }
    }//GEN-LAST:event_botonAgregarArtistaSecundarioActionPerformed

    private void buttonCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCerrarSesionActionPerformed
        cerrarSesion();
    }//GEN-LAST:event_buttonCerrarSesionActionPerformed

    private void comboBoxCancionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxCancionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboBoxCancionActionPerformed

    private void comboBoxEmpresaDiscograficaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxEmpresaDiscograficaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboBoxEmpresaDiscograficaActionPerformed

    private void comboBoxArtistaSecundarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxArtistaSecundarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboBoxArtistaSecundarioActionPerformed

    private void comboBoxInterpretePrincipalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxInterpretePrincipalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboBoxInterpretePrincipalActionPerformed

    private void BotonEstadisticasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonEstadisticasActionPerformed
       verEstadisticas();
    }//GEN-LAST:event_BotonEstadisticasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PantallaAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PantallaAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PantallaAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PantallaAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PantallaAdministrador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup AlbumOEP;
    private javax.swing.JButton BotonEstadisticas;
    private javax.swing.JLabel LabelAgregarAlbumOEp;
    private javax.swing.JLabel LabelAgregarArtista;
    private javax.swing.JLabel LabelAgregarCancionAAlbum;
    private javax.swing.JButton botonAgregarAlbum;
    private javax.swing.JButton botonAgregarArtistaSecundario;
    private javax.swing.JButton botonAgregarCancion;
    private javax.swing.JButton buttonAgregarArtista;
    private javax.swing.JButton buttonCerrarSesion;
    private javax.swing.JComboBox<String> comboBoxAlbumCancion;
    private javax.swing.JComboBox<String> comboBoxArtistaSecundario;
    private javax.swing.JComboBox<String> comboBoxCancion;
    private javax.swing.JComboBox<String> comboBoxEmpresaDiscografica;
    private javax.swing.JComboBox<String> comboBoxGeneroCancion;
    private javax.swing.JComboBox<String> comboBoxIdiomaTituloCancion;
    private javax.swing.JComboBox<String> comboBoxInterpretePrincipal;
    private javax.swing.JComboBox<String> comboBoxPais;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel labelAlbumOEp;
    private javax.swing.JLabel labelAlbumxCancion;
    private javax.swing.JLabel labelDuracionCancion;
    private javax.swing.JLabel labelFechaLanzamiento;
    private javax.swing.JLabel labelGeneroCancion;
    private javax.swing.JLabel labelIdiomaTitulo;
    private javax.swing.JLabel labelInterpretePrincipal;
    private javax.swing.JLabel labelNombreArtista;
    private javax.swing.JLabel labelNombreArtistico;
    private javax.swing.JLabel labelPais;
    private javax.swing.JLabel labelTituloAlbum;
    private javax.swing.JLabel lableTituloCancion;
    private javax.swing.JRadioButton rbuttonAlbum;
    private javax.swing.JRadioButton rbuttonEP;
    private javax.swing.JTextField textFieldDuracionCancion;
    private javax.swing.JTextField textFieldFechaLanzamiento;
    private javax.swing.JTextField textFieldNombreArtista;
    private javax.swing.JTextField textFieldNombreArtistico;
    private javax.swing.JTextField textFieldTituloAlbum;
    private javax.swing.JTextField textFieldTituloCancion;
    private javax.swing.JLabel textoResultadoAgregarAlbum;
    private javax.swing.JLabel textoResultadoAgregarArtistaSecundario;
    private javax.swing.JLabel textoResultadoAgregarCancion;
    private javax.swing.JLabel textoResultadoArtista;
    // End of variables declaration//GEN-END:variables
}
