/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Presentacion;

import Entidades.Cancion;
import Entidades.CancionMostrable;
import Entidades.CancionXPlaylist;
import Entidades.CancionXPlaylistMostrable;
import Entidades.Playlist;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import modelo.FuncionesDAO;

/**
 *
 * @author juanl
 */
public class PantallaUsuario extends javax.swing.JFrame {
    private String nickname;
    private CancionXPlaylist cancionPlaylist= new CancionXPlaylist();
    
    public void setNickname (String nickname){
        this.nickname=nickname;
    }
    public PantallaUsuario() {
        initComponents();
        listarCanciones();
    }
    public final void listarCanciones (){
        DefaultTableModel modelo = (DefaultTableModel)tablaCanciones.getModel();
        FuncionesDAO admin = new FuncionesDAO();
        List<Cancion> cancionesnormales = admin.obtenerListaCanciones();
        List<CancionMostrable> canciones =admin.obtenerListaCancionesMostrables(cancionesnormales);
        Object [] ob = new Object[4];
        for (CancionMostrable cancion: canciones){
            ob[0]= cancion.getTituloCancion();
            ob[1]= cancion.getInterptrete();
            ob[2]= cancion.getDuracion();
            ob[3]=cancion.getGenero();
            modelo.addRow(ob);
        } 
        tablaCanciones.setModel(modelo);
    }
    public final void obtenerPlaylistsUsuario(){
        DefaultTableModel modelo = (DefaultTableModel)tablaPlaylists.getModel();
        FuncionesDAO admin = new FuncionesDAO();
        List<Playlist> playlists = admin.bucarPlaylistsUsuario(nickname);
        Object [] ob = new Object[4];
        for (Playlist playlist: playlists){
            ob[0]= playlist.getId();
            ob[1]= playlist.getNombre();
            ob[2]= playlist.getTipo();
            modelo.addRow(ob);
        } 
        tablaPlaylists.setModel(modelo);
    }
    public void obtenerBusquedaCanciones(String titulo){
        DefaultTableModel modelo = (DefaultTableModel)tablaCanciones.getModel();
        FuncionesDAO admin = new FuncionesDAO();
        List<Cancion> cancionesnormales = admin.obtenerCancionesPorIds(titulo);
        List<CancionMostrable> canciones =admin.obtenerListaCancionesMostrables(cancionesnormales);
        Object [] ob = new Object[4];
        for (CancionMostrable cancion: canciones){
            ob[0]= cancion.getTituloCancion();
            ob[1]= cancion.getInterptrete();
            ob[2]= cancion.getDuracion();
            ob[3]=cancion.getGenero();
            modelo.addRow(ob);
        } 
        tablaCanciones.setModel(modelo);
    }
    public void obtenerCancionesPlayList(){
        int filaSeleccionada = tablaPlaylists.getSelectedRow();
        int idPlaylist= (int) tablaPlaylists.getValueAt(filaSeleccionada, 0);
        String nombreUser= nickname;
        DefaultTableModel modelo = (DefaultTableModel)tablaCancionesPlaylist.getModel();
        FuncionesDAO admin = new FuncionesDAO();
        List <CancionXPlaylistMostrable>canciones= admin.obtenerCancionesDeListaReproduccion(nombreUser, idPlaylist);
        Object [] ob = new Object[5];
        for (CancionXPlaylistMostrable cancion: canciones){
            ob[0]= cancion.getPosicion();
            ob[1]= cancion.getNombreCancion();
            ob[2]= cancion.getArtista();
            ob[3]= cancion.getDuracion();
            ob[4]=cancion.getGenero();
            modelo.addRow(ob);
        } 
        tablaCanciones.setModel(modelo);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pestanaUsuario = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaCanciones = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        botonBuscar = new javax.swing.JButton();
        textTituloCancion = new javax.swing.JTextField();
        verPlaylists = new javax.swing.JButton();
        botonAñadirCancion = new javax.swing.JButton();
        botonReproducirCancion = new javax.swing.JButton();
        mensajeAñadirCancion = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        errorRCancion = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaPlaylists = new javax.swing.JTable();
        modificarPlaylist = new javax.swing.JButton();
        lModificarPlaylist = new javax.swing.JLabel();
        l2AnadirCancion = new javax.swing.JLabel();
        boton2AnadirCancion = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        BcambiarNombrePlaylist = new javax.swing.JButton();
        tNuevoNombre = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        lResultadoCambiarNombre = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        rCancion = new javax.swing.JLabel();
        rArtista = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        rDuracion = new javax.swing.JLabel();
        botonLike = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        rGenero = new javax.swing.JLabel();
        textoResultadoLike = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        labelNombrePlaylist = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tablaCancionesPlaylist = new javax.swing.JTable();
        BcambiarOrdenCanciones = new javax.swing.JButton();
        BRCancion2 = new javax.swing.JButton();
        RRCanicion2 = new javax.swing.JLabel();
        numPosicion = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        ROrdenCanciones = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton2.setText("Cerrar Sesion");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        tablaCanciones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cancion", "Artista", "Duracion", "Genero"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tablaCanciones);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Ingrese titulo cancion");

        botonBuscar.setText("Buscar");
        botonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBuscarActionPerformed(evt);
            }
        });

        textTituloCancion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textTituloCancionActionPerformed(evt);
            }
        });

        verPlaylists.setText("Ver mis playlists");
        verPlaylists.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verPlaylistsActionPerformed(evt);
            }
        });

        botonAñadirCancion.setText("Añadir cancion a playlist");
        botonAñadirCancion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAñadirCancionActionPerformed(evt);
            }
        });

        botonReproducirCancion.setText("Reproducir cancion");
        botonReproducirCancion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonReproducirCancionActionPerformed(evt);
            }
        });

        mensajeAñadirCancion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        errorRCancion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textTituloCancion, javax.swing.GroupLayout.PREFERRED_SIZE, 629, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 67, Short.MAX_VALUE)
                        .addComponent(botonBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(79, 79, 79)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(botonAñadirCancion)
                                        .addComponent(verPlaylists, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 6, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(botonReproducirCancion, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(61, 61, 61))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(52, 52, 52))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 776, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(errorRCancion, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(mensajeAñadirCancion, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(30, 30, 30))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(botonBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(textTituloCancion, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(9, 9, 9)))
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(botonAñadirCancion, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(mensajeAñadirCancion, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(verPlaylists, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(botonReproducirCancion, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(errorRCancion, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 499, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(55, Short.MAX_VALUE))
        );

        pestanaUsuario.addTab("", jPanel1);

        tablaPlaylists.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "NombrePlayList", "Tipo"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tablaPlaylists);

        modificarPlaylist.setText("Modificar playlist");
        modificarPlaylist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificarPlaylistActionPerformed(evt);
            }
        });

        boton2AnadirCancion.setText("Añadir cancion a playlist");
        boton2AnadirCancion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton2AnadirCancionActionPerformed(evt);
            }
        });

        jButton8.setText("Cerrar Sesion");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        BcambiarNombrePlaylist.setText("Cambiar nombre Playlist");
        BcambiarNombrePlaylist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BcambiarNombrePlaylistActionPerformed(evt);
            }
        });

        jLabel2.setText("Nuevo nombre playlist:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 838, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(27, 27, 27))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(boton2AnadirCancion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(modificarPlaylist, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lModificarPlaylist, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(l2AnadirCancion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(61, 61, 61))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tNuevoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2)
                                    .addComponent(lResultadoCambiarNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap())))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BcambiarNombrePlaylist, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(106, 106, 106)
                        .addComponent(modificarPlaylist, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lModificarPlaylist, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21)
                        .addComponent(boton2AnadirCancion, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(l2AnadirCancion, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tNuevoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(BcambiarNombrePlaylist, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lResultadoCambiarNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 583, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(42, Short.MAX_VALUE))
        );

        pestanaUsuario.addTab("", jPanel2);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel5.setText("Reproduciendo:");

        jLabel6.setText("Cancion");

        jLabel7.setText("Duracion");

        jLabel10.setText("Artista");

        botonLike.setText("Me gusta");
        botonLike.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonLikeActionPerformed(evt);
            }
        });

        jLabel12.setIcon(new javax.swing.ImageIcon("C:\\Users\\juanl\\OneDrive\\Pictures\\Screenshots\\Captura de pantalla 2024-05-23 201112.png")); // NOI18N

        jLabel8.setText("Genero");

        textoResultadoLike.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(126, 126, 126)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(186, 186, 186)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(rGenero, javax.swing.GroupLayout.PREFERRED_SIZE, 387, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 387, Short.MAX_VALUE)
                        .addComponent(rCancion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(rArtista, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(rDuracion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 179, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addGap(154, 154, 154))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(textoResultadoLike, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(botonLike, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(133, 133, 133))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addComponent(jLabel5)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(rCancion, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rArtista, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel7))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jLabel12)))
                .addGap(10, 10, 10)
                .addComponent(rDuracion, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(botonLike, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel8)
                        .addGap(10, 10, 10)
                        .addComponent(rGenero, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(textoResultadoLike, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(134, Short.MAX_VALUE))
        );

        pestanaUsuario.addTab("", jPanel3);

        labelNombrePlaylist.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        labelNombrePlaylist.setText("Playlist: ");

        tablaCancionesPlaylist.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Posicion", "Cancion", "Artista", "Duracion", "Genero"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tablaCancionesPlaylist);

        BcambiarOrdenCanciones.setText("Cambiar Orden Canciones");
        BcambiarOrdenCanciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BcambiarOrdenCancionesActionPerformed(evt);
            }
        });

        BRCancion2.setText("Reproducir cancion");
        BRCancion2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BRCancion2ActionPerformed(evt);
            }
        });

        numPosicion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numPosicionActionPerformed(evt);
            }
        });

        jLabel3.setText("Ingrese el numero de posicion");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelNombrePlaylist)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 734, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(BcambiarOrdenCanciones, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                            .addComponent(BRCancion2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(RRCanicion2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(numPosicion)
                            .addComponent(jLabel3)
                            .addComponent(ROrdenCanciones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(62, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(labelNombrePlaylist, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 449, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(74, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(numPosicion, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(BcambiarOrdenCanciones, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ROrdenCanciones, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(BRCancion2, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(RRCanicion2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(160, 160, 160))))
        );

        pestanaUsuario.addTab("", jPanel4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pestanaUsuario)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pestanaUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 715, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public void cerrarSesion (){
        PantallaLogin pantallaLogin = new PantallaLogin();
        pantallaLogin.setVisible(true);
        dispose();
    }
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        cerrarSesion();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void botonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBuscarActionPerformed
        DefaultTableModel tabla = (DefaultTableModel)tablaCanciones.getModel();
        String tit=textTituloCancion.getText();
        tabla.setRowCount(0);
        tablaCanciones.setModel(tabla);
        if (tit == null || tit.trim().isEmpty()) {
            listarCanciones();
        }
        else{
            obtenerBusquedaCanciones(tit);
        }
    }//GEN-LAST:event_botonBuscarActionPerformed
        
    private void textTituloCancionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textTituloCancionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textTituloCancionActionPerformed

    private void verPlaylistsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verPlaylistsActionPerformed
        DefaultTableModel tabla = (DefaultTableModel)tablaPlaylists.getModel();
        tabla.setRowCount(0);
        tablaPlaylists.setModel(tabla);
        obtenerPlaylistsUsuario();
        pestanaUsuario.setSelectedIndex(1);
    }//GEN-LAST:event_verPlaylistsActionPerformed

    private void botonAñadirCancionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAñadirCancionActionPerformed
        obtenerPlaylistsUsuario();
        FuncionesDAO admin = new FuncionesDAO();
        int filaSeleccionada = tablaCanciones.getSelectedRow();
        if (filaSeleccionada != -1) {
            int idCancion = admin.convertirCancionAID((String)tablaCanciones.getValueAt(filaSeleccionada, 0));
            cancionPlaylist.setIdCancion(idCancion);
            pestanaUsuario.setSelectedIndex(1);
        }
        else{
            mensajeAñadirCancion.setText("Debe seleccionar una cancion");
        }
    }//GEN-LAST:event_botonAñadirCancionActionPerformed

    private void botonReproducirCancionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonReproducirCancionActionPerformed
        int filaSeleccionada = tablaCanciones.getSelectedRow();
        if (filaSeleccionada != -1) {
           String nombre = (String) tablaCanciones.getValueAt(filaSeleccionada, 0);
           String artista = (String) tablaCanciones.getValueAt(filaSeleccionada, 1);
           int duracion = (int) tablaCanciones.getValueAt(filaSeleccionada, 2);
           String genero = (String) tablaCanciones.getValueAt(filaSeleccionada, 3);
           CancionMostrable cancionMostrable = new CancionMostrable(nombre, artista, duracion, genero);
           rCancion.setText(cancionMostrable.getTituloCancion());
           rArtista.setText(cancionMostrable.getInterptrete());
           rDuracion.setText(String.valueOf(cancionMostrable.getDuracion()));
           rGenero.setText(cancionMostrable.getGenero());
           FuncionesDAO admin = new FuncionesDAO();
           if (admin.validarLike(nombre, nickname)){
               botonLike.setText("Ya no me gusta");
           }
           pestanaUsuario.setSelectedIndex(2);
           
        }
        else{
            errorRCancion.setText("Debe seleccionar una cancion");
        }
    }//GEN-LAST:event_botonReproducirCancionActionPerformed

    private void botonLikeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonLikeActionPerformed
        String nombre= rCancion.getText();
        FuncionesDAO admin = new FuncionesDAO();
        boolean tieneLike= admin.validarLike(nombre, nickname);
        if (tieneLike){
            boolean quito=admin.quitarLikeDelUsuario(nombre, nickname);
            if (quito){
                botonLike.setText("Me gusta");
                textoResultadoLike.setText("Se quito el like");
            }
            else{
                textoResultadoLike.setText("No se pudo quitar el like");
            }
        }
        else{
          boolean agrego=admin.añadirLikesDelUsuario(nombre, nickname);
          if (agrego){
                botonLike.setText("Ya no me gusta");
                textoResultadoLike.setText("Se añadiolike");
            }
            else{
                textoResultadoLike.setText("No se pudo añadir el like");
            }
        }
    }//GEN-LAST:event_botonLikeActionPerformed

    private void boton2AnadirCancionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton2AnadirCancionActionPerformed
        int filaSeleccionada = tablaPlaylists.getSelectedRow();
        FuncionesDAO admin = new FuncionesDAO();
        if (filaSeleccionada != -1) {
            int idPlaylist= Integer.parseInt(tablaPlaylists.getValueAt(filaSeleccionada, 0).toString());
            cancionPlaylist.setIdPlaylist(idPlaylist);
            cancionPlaylist.setNombreLista(nickname);
            cancionPlaylist.setPosicion(admin.contarCancionesPlayList(cancionPlaylist.getIdPlaylist()));
            System.out.println(cancionPlaylist.getIdCancion());
            boolean agrego=admin.anadirCancionAPlaylist(cancionPlaylist);
            if (agrego){
                l2AnadirCancion.setText("Se añadio correctamente");
            }
            else{
                l2AnadirCancion.setText("Ocurrio un problema al añadir la cancion");
            }
        }
        else{
            l2AnadirCancion.setText("Debe seleccionar una playlist");
        }
    }//GEN-LAST:event_boton2AnadirCancionActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton8ActionPerformed
    private boolean validarPosicion(int posicion){
        int cantidadCanciones= tablaCancionesPlaylist.getRowCount();
        return cantidadCanciones>=posicion && posicion>0;
    }
    
    private String obtenerNombreCancionPorPosicion(int posicion) {
        int rowCount = tablaCancionesPlaylist.getRowCount();

        for (int i = 0; i < rowCount; i++) {
            int pos = (int) tablaCancionesPlaylist.getValueAt(i, 0); 
            if (pos == posicion) {
                return (String) tablaCancionesPlaylist.getValueAt(i, 1); 
            }
        }
        return null;
    }
    
    private void BcambiarOrdenCancionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BcambiarOrdenCancionesActionPerformed
        int filaSeleccionadaP = tablaPlaylists.getSelectedRow();
        int filaSeleccionada = tablaCancionesPlaylist.getSelectedRow();
        FuncionesDAO admin = new FuncionesDAO();
        if (filaSeleccionada != -1){
            String nombreCancion= (String) tablaCancionesPlaylist.getValueAt(filaSeleccionada, 1);
            int idCancion= admin.convertirCancionAID(nombreCancion);
            int idListaReproduccion=(int) tablaPlaylists.getValueAt(filaSeleccionadaP, 0);
            System.out.println(idListaReproduccion);
            int posicion =1;
            int posicionVieja= (int) tablaCancionesPlaylist.getValueAt(filaSeleccionada, 0);
            int nuevaPosicion= Integer.parseInt(numPosicion.getText());
            int idCancionVieja= admin.convertirCancionAID(obtenerNombreCancionPorPosicion(nuevaPosicion));
            System.out.println("cancion vieja"+ idCancionVieja);
            CancionXPlaylist cancionPlaylist= new CancionXPlaylist( idCancion, nickname, idListaReproduccion, posicion);
            CancionXPlaylist cancionPlaylistVieja= new CancionXPlaylist( idCancionVieja, nickname, idListaReproduccion, posicionVieja);
            if (validarPosicion(nuevaPosicion)){
                boolean cambioVieja= admin.cambiarPosicionCancion(cancionPlaylistVieja, posicionVieja);
                System.out.println("cambioV"+cambioVieja);
                boolean cambio= admin.cambiarPosicionCancion(cancionPlaylist, nuevaPosicion);
                System.out.println("cambioN"+cambio);
                if (cambio && cambioVieja){
                    DefaultTableModel tabla = (DefaultTableModel)tablaCancionesPlaylist.getModel();
                    tabla.setRowCount(0);
                    tablaCancionesPlaylist.setModel(tabla);
                    obtenerCancionesPlayList();
                    ROrdenCanciones.setText("Cambiado Exitosamente");
                }
                else{
                    ROrdenCanciones.setText("No se pudo cambiar la posicion"); 
                }
            } 
            else {
                ROrdenCanciones.setText("La posicion es mayor a la cantidad de canciones o esta introduciendo un valor menor a 0");
            }
        }
        else{
            ROrdenCanciones.setText("Debe Seleccionar una cancion");
        }
    }//GEN-LAST:event_BcambiarOrdenCancionesActionPerformed

    private void modificarPlaylistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificarPlaylistActionPerformed
        
        int filaSeleccionada = tablaPlaylists.getSelectedRow();
        FuncionesDAO admin = new FuncionesDAO();
        if (filaSeleccionada != -1) {
            labelNombrePlaylist.setText("Playlist: "+ tablaPlaylists.getValueAt(filaSeleccionada, 1));
            obtenerCancionesPlayList();
            pestanaUsuario.setSelectedIndex(3);
        }
        else{
            lModificarPlaylist.setText("Debe seleccionar una playlist");
        }
    }//GEN-LAST:event_modificarPlaylistActionPerformed

    private void BcambiarNombrePlaylistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BcambiarNombrePlaylistActionPerformed
        int filaSeleccionada = tablaPlaylists.getSelectedRow();
        if (filaSeleccionada != -1){
            int id= (int) tablaPlaylists.getValueAt(filaSeleccionada,0);
            String nuevoNombre= tNuevoNombre.getText();
            FuncionesDAO admin = new FuncionesDAO();
            admin.cambiarNombrePlaylist(nuevoNombre, id);
            DefaultTableModel tabla = (DefaultTableModel)tablaPlaylists.getModel();
            tabla.setRowCount(0);
            tablaCanciones.setModel(tabla);
            obtenerPlaylistsUsuario(); 
            lResultadoCambiarNombre.setText("Nombre Cambiado Correctamente");
        }
        else {
            lResultadoCambiarNombre.setText("Debe seleccionar una playlist");
        }
    }//GEN-LAST:event_BcambiarNombrePlaylistActionPerformed

    private void BRCancion2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BRCancion2ActionPerformed
        int filaSeleccionada = tablaCancionesPlaylist.getSelectedRow();
        if (filaSeleccionada != -1) {
           String nombre = (String) tablaCancionesPlaylist.getValueAt(filaSeleccionada, 1);
           String artista = (String) tablaCancionesPlaylist.getValueAt(filaSeleccionada, 2);
           int duracion = (int) tablaCancionesPlaylist.getValueAt(filaSeleccionada, 3);
           String genero = (String) tablaCancionesPlaylist.getValueAt(filaSeleccionada, 4);
           CancionMostrable cancionMostrable = new CancionMostrable(nombre, artista, duracion, genero);
           rCancion.setText(cancionMostrable.getTituloCancion());
           rArtista.setText(cancionMostrable.getInterptrete());
           rDuracion.setText(String.valueOf(cancionMostrable.getDuracion()));
           rGenero.setText(cancionMostrable.getGenero());
           FuncionesDAO admin = new FuncionesDAO();
           if (admin.validarLike(nombre, nickname)){
               botonLike.setText("Ya no me gusta");
           }
           pestanaUsuario.setSelectedIndex(2);
           
        }
        else{
            RRCanicion2.setText("Debe seleccionar una cancion");
        }
    }//GEN-LAST:event_BRCancion2ActionPerformed

    private void numPosicionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numPosicionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numPosicionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PantallaUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PantallaUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PantallaUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PantallaUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PantallaUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BRCancion2;
    private javax.swing.JButton BcambiarNombrePlaylist;
    private javax.swing.JButton BcambiarOrdenCanciones;
    private javax.swing.JLabel ROrdenCanciones;
    private javax.swing.JLabel RRCanicion2;
    private javax.swing.JButton boton2AnadirCancion;
    private javax.swing.JButton botonAñadirCancion;
    private javax.swing.JButton botonBuscar;
    private javax.swing.JButton botonLike;
    private javax.swing.JButton botonReproducirCancion;
    private javax.swing.JLabel errorRCancion;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel l2AnadirCancion;
    private javax.swing.JLabel lModificarPlaylist;
    private javax.swing.JLabel lResultadoCambiarNombre;
    private javax.swing.JLabel labelNombrePlaylist;
    private javax.swing.JLabel mensajeAñadirCancion;
    private javax.swing.JButton modificarPlaylist;
    private javax.swing.JTextField numPosicion;
    private javax.swing.JTabbedPane pestanaUsuario;
    private javax.swing.JLabel rArtista;
    private javax.swing.JLabel rCancion;
    private javax.swing.JLabel rDuracion;
    private javax.swing.JLabel rGenero;
    private javax.swing.JTextField tNuevoNombre;
    private javax.swing.JTable tablaCanciones;
    private javax.swing.JTable tablaCancionesPlaylist;
    private javax.swing.JTable tablaPlaylists;
    private javax.swing.JTextField textTituloCancion;
    private javax.swing.JLabel textoResultadoLike;
    private javax.swing.JButton verPlaylists;
    // End of variables declaration//GEN-END:variables
}
